#ifndef SNAKE_DIRECTION_HPP
#define SNAKE_DIRECTION_HPP

enum SnakeDirection {
    SNAKE_FORWARD,
    SNAKE_BACKWARD,
    SNAKE_LEFT,
    SNAKE_RIGHT,
    SNAKE_UP,
    SNAKE_DOWN
};

#endif // !SNAKE_DIRECTION_HPP
